#PUNTO 2.1
SELECT 
    P.ORDEN_NO,
    P.FECHA_PEDIDO,
    A.ARTICULO,
    IFNULL(A.NOMBRE_ARTICULO, 'INEXISTENTE') AS NOMBRE_ARTICULO,
    IFNULL(A.PRECIO_UNITARIO, - 1) AS PRECIO_UNITARIO,
    P.VLRTOTAL,
    CASE
        WHEN A.ESTADO = 'INACTIVO' THEN 'FUERA DE STOCK'
        ELSE 'EN STOCK'
    END AS ESTADO
FROM
    PEDIDOS AS P
	LEFT JOIN
    ARTICULOS AS A ON P.ARTICULO = A.ARTICULO
WHERE
    P.FECHA_PEDIDO BETWEEN DATE('2021-01-01') AND DATE('2022-05-31');