#PUNTO 2.2
SELECT 
    P.CLIENTE, P.FECHA_PEDIDO, P.ARTICULO, P.VLRTOTAL
FROM
    PEDIDOS AS P
	LEFT JOIN
    ARTICULOS AS A ON P.ARTICULO = A.ARTICULO
WHERE
    A.ESTADO != 'INACTIVO'
    AND
    P.FECHA_PEDIDO >= DATE('2018-05-01')
