#CREATES
CREATE TABLE PEDIDO
(
   ID INT PRIMARY KEY NOT NULL,
   ORDEN_NO VARCHAR(25) NOT NULL,
   TIPO varchar(30) NOT NULL,
   FECHA_PEDIDO DATE,
   VLRTOTAL INT,
   CLIENTE INT,
   ARTICULO INT,
   FOREIGN KEY (ARTICULO) REFERENCES ARTICULO(ARTICULO)
);

CREATE TABLE ARTICULO
(
	ARTICULO INT PRIMARY KEY NOT NULL,
    NOMBRE_ARTICULO VARCHAR(25) NOT NULL,
    PRECIO_UNITARIO INT,
    ESTADO VARCHAR(25) NOT NULL
);